[aws]
34.239.89.6

[local]
192.168.1.28

[uptime_monitors:children]
aws
local

[aws:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/uptime-monitor-key.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
monitor_user=ubuntu

[local:vars]
ansible_user=s4pynk0
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_become_password={{ vault_become_password }}
monitor_user=s4pynk0